### ISSUE TITLE
The React-Router-v4-mdc component demo isn't correct. 

### ISSUE THREAD

**Issue by Kolhar730** [Kolhar730/react-router-v4-components#2]
The demo is currently present on https://codesandbox.io/s/8nrz8o6x00. 
However, there's seems to be a problem with how the project is rendered. If anyone understands why this is so and can help me correct it. It'll be great!

Thanks.

**Comment by Tensai66** [comment]
What, exactly should it look like?

**Comment by Kolhar730** [comment]
The details for the same has been mentioned on the component's README file. [Link](https://github.com/Kolhar730/react-router-v4-simple-and-mdc/blob/master/simple-react-router-v4-mdc/README.md)

**Comment by Kolhar730** [comment]
Fixed the issue.
